# Generated by Django 5.2.1 on 2025-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('clothes', 'Clothes'), ('books', 'Books'), ('other', 'Other')], max_length=100),
        ),
    ]
